services:
  kp-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kp-web
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - '3000:3000'
    restart: always
